language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - 2.2.0
  - jruby-19mode

before_install:
  - gem install bundler -v 1.11

env:
  global:
    - "JRUBY_OPTS=-Xcext.enabled=true"

script: bundle exec rspec
